### Exercise 1:

In [2]:
import gymnasium as gym
import numpy as np

env = gym.make("FrozenLake-v1", is_slippery=True)

env.reset()

print(f"Espace d'actions : {env.action_space}")
print(f"Espace d'observations : {env.observation_space}")

for _ in range(10):
    action = env.action_space.sample()
    observation, reward, done, _, _ = env.step(action)
    print(f"Action : {action}, Observation : {observation}, Reward : {reward}")

Espace d'actions : Discrete(4)
Espace d'observations : Discrete(16)
Action : 2, Observation : 4, Reward : 0.0
Action : 1, Observation : 5, Reward : 0.0
Action : 1, Observation : 5, Reward : 0
Action : 2, Observation : 5, Reward : 0
Action : 1, Observation : 5, Reward : 0
Action : 2, Observation : 5, Reward : 0
Action : 0, Observation : 5, Reward : 0
Action : 3, Observation : 5, Reward : 0
Action : 3, Observation : 5, Reward : 0
Action : 0, Observation : 5, Reward : 0


### Exercise 2:

In [4]:
q_table = np.zeros((env.observation_space.n, env.action_space.n))

print("Q-Table initialise:")
print(q_table)

Q-Table initialise:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Exercise 3:

In [5]:
alpha = 0.1  #vitesse l'agent apprend.Valeur de 0.1 -> l'agent met à jour ses connaissances à 10%
# de la différence entre l'ancienne et la nouvelle estimation.

gamma = 0.99  # l'importance des récompenses futures.valeur de 0.99 -> l'agent valorise récompenses futures

epsilon = 1.0  # Contrôle la probabilité que l'agent explore.  epsilon est à 1.0 -> l'agent explore beaucoup

epsilon_decay = 0.995  # Réduit progressivement epsilon après chaque épisode

num_episodes = 5000  # Nombre total de fois que l'agent va jouer dans l'environnement pour apprendre

for episode in range(num_episodes): # exécute l'apprentissage sur un nombre fixe d'épisodes (num_episodes).
    state, _ = env.reset() # réinitialise l'environnement
    done = False
    
    while not done:
        # choisir l'action
        if np.random.rand() < epsilon:
            action = env.action_space.sample()  # choisit une action aléatoire (exploration)
        else:
            # choisit l'action avec la valeur Q la plus élevée pour l'état actuel (exploitation)
            action = np.argmax(q_table[state])
        
        # exécute l'action choisie par l'agent et observe le nouvel état, la récompense
        next_state, reward, done, _, _ = env.step(action)
        
        # met à jour la Q-Table avec la formule de Q-Learning.Combine la récompense immédiate et la récompense future estimée pour améliorer les décisions de l'agent
        q_table[state, action] = q_table[state, action] + alpha * (reward + gamma * np.max(q_table[next_state]) - q_table[state, action])
        
        # L'agent passe à l'état suivant pour continuer à explorer ou exploiter l'environnement
        state = next_state
    
    # epsilon est réduit pour que l'agent explore moins et exploite plus au fur et à mesure qu'il apprend
    epsilon *= epsilon_decay

In [6]:
print(q_table)

[[4.53060828e-01 3.62493811e-01 3.62411220e-01 3.63306112e-01]
 [6.29494663e-03 3.35465242e-02 4.99766808e-02 3.96763595e-01]
 [3.46923725e-01 5.53584074e-02 6.05847975e-02 1.80739355e-02]
 [1.47192259e-07 4.01536966e-10 1.12178777e-08 1.07952092e-01]
 [4.62325154e-01 2.15215253e-01 2.51168171e-01 1.76359536e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.74336586e-02 9.16010432e-02 2.62636793e-01 2.13510393e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.75890364e-01 2.67624889e-01 2.13034272e-01 4.84436415e-01]
 [2.82424219e-01 5.44371478e-01 4.01370623e-01 2.29579722e-01]
 [5.36636764e-01 1.33531274e-01 1.92413983e-01 8.77381576e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.37560209e-01 3.20346491e-01 5.93772700e-01 3.56205992e-01]
 [3.03326579e-01 3.87463459e-01 7.64179477e-01 5.28765716e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000

### Exercise 4:

In [7]:
num_test_episodes = 100 # Nombre d'épisodes de test que l'agent va jouer
successes = 0 # Compteur pour n fois où l'agent réussit à atteindre l'objectif.

for _ in range(num_test_episodes):
    state, _ = env.reset()
    done = False
    
    while not done:
        # L'agent choisit toujours l'action optimale en fonction de la Q-Table.Ne fait plus d'exploration, seulement de l'exploitation
        action = np.argmax(q_table[state])  
        
        next_state, reward, done, _, _ = env.step(action)  # exécute l'action choisie par l'agent
        
        state = next_state # passe à l'état suivant pour continuer à jouer jusqu'à la fin de l'épisode
    if reward == 1:
        successes += 1 # augmenter le compteur si la recompense est 1

success_rate = successes / num_test_episodes # calculer le pourcentage de reussite
print(f"Success rate: {success_rate * 100}%")

Success rate: 68.0%
